PacletObject[<|
	"Name" -> "ChernSimons",
	"Version" -> "0.7.0",
	"WolframVersion" -> "13.0+",
	"Description" -> "Involutive bi-Lie infinity structures on cyclic words: the exterior and symmetric conventions, the shift isomorphisms between them, the bracket and co-bracket, the pairings, and the defining identities, together with Sullivan minimal models, the test for Hodge type, the nondegenerate quotient and the canonical Maurer-Cartan element it carries. ChernSimons` is one context: fifty-five documented CamelCase exports over an arbitrary graded alphabet, and below them the engine of the Chern-Simons computations on the circle, carrying the Maurer-Cartan, BV, A-infinity and gauge layers.",
	"Creator" -> "Pavel Hajek",
	"License" -> "MIT",
	"Extensions" -> {
		{"Kernel", "Root" -> "Kernel",
			"Context" -> {{"ChernSimons`", "ChernSimons.wl"}},
			"Symbols" -> {"ChernSimons`GradedPairing", "ChernSimons`CyclicWord", "ChernSimons`CyclicWords",
				"ChernSimons`WordDegree", "ChernSimons`ExteriorProduct", "ChernSimons`SymmetricProduct",
				"ChernSimons`ChordContraction", "ChernSimons`InvolutiveBracket", "ChernSimons`InvolutiveCobracket", "ChernSimons`CyclicDifferential",
				"ChernSimons`ShiftIsomorphism",
				"ChernSimons`DualPairing", "ChernSimons`ProductPairing", "ChernSimons`KoszulSign",
				"ChernSimons`JacobiObstruction", "ChernSimons`CoJacobiObstruction", "ChernSimons`DrinfeldObstruction",
				"ChernSimons`InvolutivityObstruction", "ChernSimons`$DefiningIdentities",
				"ChernSimons`BeilinsonDrinfeldOperator", "ChernSimons`BeilinsonDrinfeldBracket",
				"ChernSimons`BeilinsonDrinfeldMasterEquation", "ChernSimons`BeilinsonDrinfeldMasterQ", "ChernSimons`PlanckDegree",
				"ChernSimons`MaurerCartanEquation", "ChernSimons`MaurerCartanQ",
				"ChernSimons`MaurerCartanBasis", "ChernSimons`MaurerCartanAnsatz",
				"ChernSimons`TwistedDifferential", "ChernSimons`TwistedCobracket", "ChernSimons`HBar",
				"ChernSimons`GaugeFlow",
				"ChernSimons`AInfinityAlgebra", "ChernSimons`AInfinityOperation",
				"ChernSimons`AInfinityObstruction", "ChernSimons`AInfinityQ",
				"ChernSimons`AInfinityMorphismObstruction", "ChernSimons`AInfinityMorphismQ",
				"ChernSimons`SullivanModel", "ChernSimons`$SullivanModels", "ChernSimons`SullivanModelBasis",
				"ChernSimons`SullivanModelProduct", "ChernSimons`SullivanModelDifferential",
				"ChernSimons`SullivanModelOrientation", "ChernSimons`SullivanModelPairing",
				"ChernSimons`DegenerateSubspace", "ChernSimons`HodgeTypeQ",
				"ChernSimons`HodgeTypeReport", "ChernSimons`NondegenerateQuotient",
				"ChernSimons`CanonicalMaurerCartan",
				"ChernSimons`PoincareDualityAlgebra", "ChernSimons`GradedPairingQ", "ChernSimons`SullivanModelQ", "ChernSimons`PoincareDualityAlgebraQ", "ChernSimons`AInfinityAlgebraQ"}},
		{"Documentation", "Root" -> "Documentation", "Language" -> "English"}
	}
|>]
